version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: ckbtc-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ckbtc-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: ckbtcPassw
    ports:
      - "3306:3306"