version: "3.9"
networks:
  ckbtc-network:

services:
  mysql:
    image: mysql:8.0
    container_name: ckbtc-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: ckbtc-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: ckbtcPassw
    networks:
      - ckbtc-network
    ports:
      - "3306:3306"
  redis:
    image: redis:6.2.6-alpine
    container_name: ckbtc-redis
    restart: always
    networks:
      - ckbtc-network
    ports:
      - "6379:6379"
  app:
    image: app
    container_name: ckbtc-api
    restart: always
    networks:
      - ckbtc-network
    ports:
      - '3000:3000'
